void reset_to_98(int *);
void swap_int(int *, int *);
int _strlen(char *);
void _puts(char *);
int _putchar(char c);
void print_rev(char *);
void rev_string(char *);
void puts2(char *);
void puts_half(char *str);
void print_array(int *a, int n);
char *_strcpy(char *dest, char *src);
